import type { Word } from "./schema";

/**
 * Vocabulary.
 *
 * `rootIndices` are LETTER positions within `hebrew` (vowel points do not count).
 * The content test asserts, for every entry, that the letters those indices
 * select are a subsequence of the declared root — which catches both mis-indexed
 * roots and words filed under the wrong root.
 *
 * Weak roots legitimately show fewer than three letters in a given form (a
 * III-he verb loses its final ה, a geminate root collapses), so two indices is
 * valid where the form genuinely only exposes two root consonants.
 */
export const words: Word[] = [
  // ---- Genesis 1:1 ----
  {
    id: "bereshit",
    rootId: "ראשׁ",
    hebrew: "בְּרֵאשִׁית",
    translit: "bərēʾšîṯ",
    gloss: "in the beginning",
    partOfSpeech: "noun",
    rootIndices: [1, 2, 3],
    attestations: ["Genesis 1:1"],
    distractors: ["in the heavens", "on the earth", "in the darkness"],
    notes: "Prefixed בְּ (\"in\") on רֵאשִׁית (\"beginning, first part\"), from the root ר־א־שׁ \"head\".",
  },
  {
    id: "bara",
    rootId: "ברא",
    hebrew: "בָּרָא",
    translit: "bārāʾ",
    gloss: "he created",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: ["Genesis 1:1"],
    distractors: ["he saw", "he called", "he blessed"],
  },
  {
    id: "elohim",
    rootId: "אלה",
    hebrew: "אֱלֹהִים",
    translit: "ʾĕlōhîm",
    gloss: "God",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: ["Genesis 1:1", "Genesis 1:3"],
    distractors: ["heavens", "spirit", "beginning"],
    notes: "Plural in form; takes a singular verb when it refers to the God of Israel.",
  },
  {
    id: "el",
    rootId: "אלה",
    hebrew: "אֵל",
    translit: "ʾēl",
    gloss: "God, a god",
    partOfSpeech: "noun",
    rootIndices: [0, 1],
    attestations: [],
    distractors: ["king", "spirit", "man"],
    notes: "The short form beside אֱלֹהִים. Survives in names like יִשְׂרָאֵל (Israel) and גַּבְרִיאֵל (Gabriel).",
  },
  {
    id: "shamayim",
    rootId: "שׁמי",
    hebrew: "הַשָּׁמַיִם",
    translit: "haššāmayim",
    gloss: "the heavens",
    partOfSpeech: "noun",
    rootIndices: [1, 2, 3],
    attestations: ["Genesis 1:1"],
    distractors: ["the earth", "the waters", "the light"],
    notes: "Definite article הַ + שָׁמַיִם, a dual-form noun.",
  },
  {
    id: "erets",
    rootId: "ארץ",
    hebrew: "הָאָרֶץ",
    translit: "hāʾāreṣ",
    gloss: "the earth",
    partOfSpeech: "noun",
    rootIndices: [1, 2, 3],
    attestations: ["Genesis 1:1"],
    distractors: ["the heavens", "the sea", "the field"],
  },

  // ---- Genesis 1:3-5 ----
  {
    id: "vayomer",
    rootId: "אמר",
    hebrew: "וַיֹּאמֶר",
    translit: "wayyōʾmer",
    gloss: "and he said",
    partOfSpeech: "verb",
    rootIndices: [2, 3, 4],
    parse: { binyan: "qal", tense: "imperfect", person: "3", gender: "m", number: "s" },
    attestations: ["Genesis 1:3"],
    distractors: ["and he saw", "and he made", "and he called"],
    notes: "Waw-consecutive + imperfect — the standard past-narrative form. The root's א is quiescent here.",
  },
  {
    id: "or",
    rootId: "אור",
    hebrew: "אוֹר",
    translit: "ʾôr",
    gloss: "light",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: ["Genesis 1:3", "Genesis 1:4"],
    distractors: ["water", "sky", "land"],
  },
  {
    id: "yehi",
    rootId: "היה",
    hebrew: "יְהִי",
    translit: "yəhî",
    gloss: "let there be",
    partOfSpeech: "verb",
    rootIndices: [1, 2],
    parse: { binyan: "qal", tense: "jussive", person: "3", gender: "m", number: "s" },
    attestations: ["Genesis 1:3"],
    distractors: ["there was", "he made", "let him see"],
    notes: "Jussive of ה־י־ה. The final root ה drops away, leaving only ה and י visible.",
  },
  {
    id: "tov",
    rootId: "טוב",
    hebrew: "טוֹב",
    translit: "ṭôḇ",
    gloss: "good",
    partOfSpeech: "adjective",
    rootIndices: [0, 1, 2],
    attestations: ["Genesis 1:4"],
    distractors: ["great", "holy", "many"],
  },
  {
    id: "choshekh",
    rootId: "חשׁך",
    hebrew: "חֹשֶׁךְ",
    translit: "ḥōšeḵ",
    gloss: "darkness",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: ["Genesis 1:4"],
    distractors: ["light", "evening", "deep"],
  },
  {
    id: "yom",
    rootId: "יום",
    hebrew: "יוֹם",
    translit: "yôm",
    gloss: "day",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: ["Genesis 1:5"],
    distractors: ["night", "morning", "year"],
  },
  {
    id: "laylah",
    rootId: "ליל",
    hebrew: "לָיְלָה",
    translit: "lāyəlâ",
    gloss: "night",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: ["Genesis 1:5"],
    distractors: ["day", "evening", "darkness"],
  },
  {
    id: "vayar",
    rootId: "ראה",
    hebrew: "וַיַּרְא",
    translit: "wayyarʾ",
    gloss: "and he saw",
    partOfSpeech: "verb",
    rootIndices: [2, 3],
    parse: { binyan: "qal", tense: "imperfect", person: "3", gender: "m", number: "s" },
    attestations: ["Genesis 1:4"],
    distractors: ["and he said", "and he called", "and he rested"],
    notes: "From ר־א־ה. As a III-he verb the final ה is lost in the short imperfect.",
  },

  // ---- Root שׁ־מ־ר ----
  {
    id: "shamar",
    rootId: "שׁמר",
    hebrew: "שָׁמַר",
    translit: "šāmar",
    gloss: "he guarded, he kept",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he opened", "he remembered", "he wrote"],
  },
  {
    id: "shomer",
    rootId: "שׁמר",
    hebrew: "שֹׁמֵר",
    translit: "šōmēr",
    gloss: "one who guards, keeper",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "participle", gender: "m", number: "s" },
    attestations: [],
    distractors: ["king", "gate", "shepherd"],
    notes: "Qal active participle — the ō-ē vowel pattern is the participle's signature.",
  },
  {
    id: "mishmeret",
    rootId: "שׁמר",
    hebrew: "מִשְׁמֶרֶת",
    translit: "mišmereṯ",
    gloss: "watch, guard duty",
    partOfSpeech: "noun",
    rootIndices: [1, 2, 3],
    attestations: [],
    distractors: ["covenant", "blessing", "morning"],
    notes: "Prefixed מ־ noun: a very common way Hebrew builds nouns off a verbal root.",
  },
  {
    id: "yishmor",
    rootId: "שׁמר",
    hebrew: "יִשְׁמֹר",
    translit: "yišmōr",
    gloss: "he will guard",
    partOfSpeech: "verb",
    rootIndices: [1, 2, 3],
    parse: { binyan: "qal", tense: "imperfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he guarded", "they guarded", "guard!"],
  },
  {
    id: "shamru",
    rootId: "שׁמר",
    hebrew: "שָׁמְרוּ",
    translit: "šāmərû",
    gloss: "they guarded",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "perfect", person: "3", gender: "c", number: "p" },
    attestations: [],
    distractors: ["he guarded", "I guarded", "he will guard"],
  },

  // ---- Psalm 23 ----
  {
    id: "mizmor",
    rootId: "זמר",
    hebrew: "מִזְמוֹר",
    translit: "mizmôr",
    gloss: "psalm, song",
    partOfSpeech: "noun",
    rootIndices: [1, 2, 4],
    attestations: ["Psalm 23:1"],
    distractors: ["prayer", "blessing", "lament"],
    notes: "Another prefixed מ־ noun, from ז־מ־ר \"make music\".",
  },
  {
    id: "roi",
    rootId: "רעה",
    hebrew: "רֹעִי",
    translit: "rōʿî",
    gloss: "my shepherd",
    partOfSpeech: "noun",
    rootIndices: [0, 1],
    attestations: ["Psalm 23:1"],
    distractors: ["my judge", "my king", "my rock"],
    notes: "Qal participle רֹעֶה with the 1st-person suffix ־ִי. The root's final ה gives way to the suffix.",
  },
  {
    id: "roeh",
    rootId: "רעה",
    hebrew: "רֹעֶה",
    translit: "rōʿeh",
    gloss: "shepherd",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: [],
    distractors: ["judge", "prophet", "priest"],
  },
  {
    id: "echsar",
    rootId: "חסר",
    hebrew: "אֶחְסָר",
    translit: "ʾeḥsār",
    gloss: "I shall lack",
    partOfSpeech: "verb",
    rootIndices: [1, 2, 3],
    parse: { binyan: "qal", tense: "imperfect", person: "1", gender: "c", number: "s" },
    attestations: ["Psalm 23:1"],
    distractors: ["I shall rest", "I shall fear", "I shall return"],
    notes: "The א־ prefix marks 1st person singular imperfect.",
  },

  // ---- Root א־ה־ב ----
  {
    id: "ahav",
    rootId: "אהב",
    hebrew: "אָהַב",
    translit: "ʾāhaḇ",
    gloss: "he loved",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he hated", "he chose", "he feared"],
  },
  {
    id: "ahavah",
    rootId: "אהב",
    hebrew: "אַהֲבָה",
    translit: "ʾahăḇâ",
    gloss: "love",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: [],
    distractors: ["mercy", "truth", "peace"],
  },
  {
    id: "ohev",
    rootId: "אהב",
    hebrew: "אֹהֵב",
    translit: "ʾōhēḇ",
    gloss: "loving, one who loves",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "participle", gender: "m", number: "s" },
    attestations: [],
    distractors: ["hating", "fearing", "seeking"],
  },

  // ---- Root ד־ב־ר ----
  {
    id: "davar",
    rootId: "דבר",
    hebrew: "דָּבָר",
    translit: "dāḇār",
    gloss: "word, thing, matter",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: [],
    distractors: ["name", "voice", "way"],
  },
  {
    id: "devar",
    rootId: "דבר",
    hebrew: "דְּבַר",
    translit: "dəḇar",
    gloss: "word of (construct)",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: [],
    distractors: ["word (absolute)", "words", "his word"],
    notes: "Construct form of דָּבָר. The first vowel reduces because the stress moves onto the following word.",
  },
  {
    id: "dibber",
    rootId: "דבר",
    hebrew: "דִּבֶּר",
    translit: "dibber",
    gloss: "he spoke",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "piel", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he wrote", "he called", "he heard"],
    notes: "Piel. The doubled middle root letter (dagesh in the ב) is the piel's fingerprint.",
  },

  // ---- Binyanim: ג־ד־ל and ל־מ־ד ----
  {
    id: "gadal",
    rootId: "גדל",
    hebrew: "גָּדַל",
    translit: "gāḏal",
    gloss: "he was great, he grew",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he made great", "he magnified", "he fell"],
  },
  {
    id: "giddel",
    rootId: "גדל",
    hebrew: "גִּדֵּל",
    translit: "giddēl",
    gloss: "he raised, he brought up",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "piel", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he was great", "he was raised", "he magnified himself"],
  },
  {
    id: "higdil",
    rootId: "גדל",
    hebrew: "הִגְדִּיל",
    translit: "hiḡdîl",
    gloss: "he magnified, he made great",
    partOfSpeech: "verb",
    rootIndices: [1, 2, 4],
    parse: { binyan: "hiphil", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he was great", "he raised", "he was magnified"],
    notes: "Hiphil: the הִ־ prefix plus a long î before the last root letter.",
  },
  {
    id: "lamad",
    rootId: "למד",
    hebrew: "לָמַד",
    translit: "lāmaḏ",
    gloss: "he learned",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he taught", "he wrote", "he asked"],
  },
  {
    id: "limmed",
    rootId: "למד",
    hebrew: "לִמַּד",
    translit: "limmaḏ",
    gloss: "he taught",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "piel", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he learned", "he was taught", "he studied"],
    notes: "Piel of ל־מ־ד. Qal \"learn\" becomes piel \"cause to learn\" — that is, teach.",
  },

  // ---- Ruth ----
  {
    id: "am",
    rootId: "עמם",
    hebrew: "עַם",
    translit: "ʿam",
    gloss: "people",
    partOfSpeech: "noun",
    rootIndices: [0, 1],
    attestations: ["Ruth 1:16"],
    distractors: ["city", "family", "nation (foreign)"],
    notes: "Geminate root: the second מ reappears when a suffix is added — עַמִּי \"my people\".",
  },
  {
    id: "halakh",
    rootId: "הלך",
    hebrew: "הָלַךְ",
    translit: "hālaḵ",
    gloss: "he walked, he went",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: ["Ruth 1:16"],
    distractors: ["he returned", "he stood", "he sat"],
  },
  {
    id: "shuv",
    rootId: "שׁוב",
    hebrew: "שׁוּב",
    translit: "šûḇ",
    gloss: "to return",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "infinitive_construct" },
    attestations: ["Ruth 1:16"],
    distractors: ["to go", "to dwell", "to rest"],
    notes: "A hollow (II-waw) root: the ו behaves as a vowel through most of the paradigm.",
  },
  {
    id: "melekh",
    rootId: "מלך",
    hebrew: "מֶלֶךְ",
    translit: "meleḵ",
    gloss: "king",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    attestations: [],
    distractors: ["servant", "prophet", "priest"],
  },
  {
    id: "katav",
    rootId: "כתב",
    hebrew: "כָּתַב",
    translit: "kāṯaḇ",
    gloss: "he wrote",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he read", "he spoke", "he sent"],
  },
  {
    id: "shofet",
    rootId: "שׁפט",
    hebrew: "שֹׁפֵט",
    translit: "šōp̄ēṭ",
    gloss: "judge, one who judges",
    partOfSpeech: "noun",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "participle", gender: "m", number: "s" },
    attestations: [],
    distractors: ["shepherd", "keeper", "king"],
    notes: "Same ō-ē participle pattern as שֹׁמֵר and רֹעֶה — once you see it, you can read it anywhere.",
  },
  {
    id: "vayiqra",
    rootId: "קרא",
    hebrew: "וַיִּקְרָא",
    translit: "wayyiqrāʾ",
    gloss: "and he called",
    partOfSpeech: "verb",
    rootIndices: [2, 3, 4],
    parse: { binyan: "qal", tense: "imperfect", person: "3", gender: "m", number: "s" },
    attestations: ["Genesis 1:5"],
    distractors: ["and he said", "and he saw", "and he made"],
  },
  {
    id: "qara",
    rootId: "קרא",
    hebrew: "קָרָא",
    translit: "qārāʾ",
    gloss: "he called",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "qal", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: ["Genesis 1:5"],
    distractors: ["he created", "he guarded", "he loved"],
  },
  {
    id: "barakh",
    rootId: "ברך",
    hebrew: "בָּרַךְ",
    translit: "bāraḵ",
    gloss: "he blessed",
    partOfSpeech: "verb",
    rootIndices: [0, 1, 2],
    parse: { binyan: "piel", tense: "perfect", person: "3", gender: "m", number: "s" },
    attestations: [],
    distractors: ["he created", "he kept", "he called"],
  },
  {
    id: "qadosh",
    rootId: "קדשׁ",
    hebrew: "קָדוֹשׁ",
    translit: "qāḏôš",
    gloss: "holy",
    partOfSpeech: "adjective",
    rootIndices: [0, 1, 3],
    attestations: [],
    distractors: ["good", "great", "faithful"],
  },
];

export const wordById = new Map(words.map((w) => [w.id, w]));
